apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "helm.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort }}-tcp
  wildcardPolicy: None
