graph:
  storeProperties:
    gaffer.store.class: uk.gov.gchq.gaffer.federatedstore.FederatedStore
    gaffer.store.properties.class: uk.gov.gchq.gaffer.federatedstore.FederatedStoreProperties
    gaffer.serialiser.json.modules: uk.gov.gchq.gaffer.sketches.serialisation.json.SketchesJsonModules
  operationDeclarations: [ {
    "operation": "uk.gov.gchq.gaffer.operation.impl.generate.GenerateElements",
    "handler": {
      "class": "uk.gov.gchq.gaffer.store.operation.handler.generate.GenerateElementsHandler"
    }
  } ]