{{- if .Values.rest.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-ui
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ui/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image:  {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /usr/share/nginx/html/{{ .Values.ui.envConfigFile }}
              name: env-js-config
              subPath: {{ .Values.ui.envConfigFile }}
      volumes:
        - name: env-js-config
          configMap:
            name: {{ include "helm.fullname" . }}-ui
            items:
            - key: "web.properties"
              path: {{ .Values.ui.envConfigFile }}
{{- end }}